CREATE TABLE `characters` (
    `id` int unsigned NOT NULL AUTO_INCREMENT,
    `account_id` int NOT NULL,
    `world_id` int NOT NULL,
    `name` varchar(13) NOT NULL,
    `level` int NOT NULL DEFAULT 1,
    `exp` int NOT NULL DEFAULT 0,
    `gacha_exp` int NOT NULL DEFAULT 0,
    `str` int NOT NULL DEFAULT 4,
    `dex` int NOT NULL DEFAULT 4,
    `luk` int NOT NULL DEFAULT 4,
    `int` int NOT NULL DEFAULT 4,
    `hp` int NOT NULL DEFAULT 50,
    `mp` int NOT NULL DEFAULT 5,
    `max_hp` int NOT NULL DEFAULT 50,
    `max_mp` int NOT NULL DEFAULT 5,
    `mesos` int NOT NULL DEFAULT 0,
    `job` int NOT NULL,
    `skin_colour` int NOT NULL,
    `gender` int NOT NULL,
    `fame` int NOT NULL DEFAULT 0,
    `hair` int NOT NULL,
    `face` int NOT NULL,
    `ap` int NOT NULL DEFAULT 0,
    `sp` json NOT NULL,
    `map` int NOT NULL,
    `spawn_point` int NOT NULL DEFAULT 0,
    `gm` int NOT NULL DEFAULT 0,
    `party` int,
    `buddy_capacity` int NOT NULL DEFAULT 25,
    `created_at` datetime NOT NULL DEFAULT NOW(),
    `rank` int NOT NULL DEFAULT 0,
    `rank_move` int NOT NULL DEFAULT 0,
    `job_rank` int NOT NULL DEFAULT 0,
    `job_rank_move` int NOT NULL DEFAULT 0,
    `guild` int,
    `guild_rank` int,
    `slots` json NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB;
