CREATE TABLE `equipment` (
  `id` int NOT NULL AUTO_INCREMENT,
  `item_id` int NOT NULL,
  `character_id` int NOT NULL,
  `position` int NOT NULL,
  `amount` int NOT NULL DEFAULT 1,
  `upgrade_slots` int NOT NULL DEFAULT 0,
  `level` int NOT NULL DEFAULT 0,
  `item_level` int NOT NULL DEFAULT 1,
  `exp` int NOT NULL DEFAULT 0,
  `str` int NOT NULL DEFAULT 0,
  `dex` int NOT NULL DEFAULT 0,
  `int` int NOT NULL DEFAULT 0,
  `luk` int NOT NULL DEFAULT 0,
  `hp` int NOT NULL DEFAULT 0,
  `mp` int NOT NULL DEFAULT 0,
  `w_atk` int NOT NULL DEFAULT 0,
  `m_atk` int NOT NULL DEFAULT 0,
  `w_def` int NOT NULL DEFAULT 0,
  `m_def` int NOT NULL DEFAULT 0,
  `acc` int NOT NULL DEFAULT 0,
  `avoid` int NOT NULL DEFAULT 0,
  `hands` int NOT NULL DEFAULT 0,
  `speed` int NOT NULL DEFAULT 0,
  `jump` int NOT NULL DEFAULT 0,
  `locked` int NOT NULL DEFAULT 0,
  `vicious` int NOT NULL DEFAULT 0,
  `owner` varchar(13) NOT NULL DEFAULT '',
  `flag` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB;