-- Table Definition ----------------------------------------------

CREATE TABLE characters (
    id SERIAL PRIMARY KEY,
    account_id integer NOT NULL DEFAULT 0,
    world_id integer NOT NULL DEFAULT 0,
    name character varying(13) NOT NULL DEFAULT ''::character varying,
    level smallint NOT NULL DEFAULT 1,
    exp integer NOT NULL DEFAULT 0,
    gacha_exp integer NOT NULL DEFAULT 0,
    str smallint NOT NULL DEFAULT 12,
    dex smallint NOT NULL DEFAULT 5,
    luk smallint NOT NULL DEFAULT 4,
    int smallint NOT NULL DEFAULT 4,
    hp smallint NOT NULL DEFAULT 50,
    mp smallint NOT NULL DEFAULT 5,
    max_hp smallint NOT NULL DEFAULT 50,
    max_mp smallint NOT NULL DEFAULT 5,
    mesos integer NOT NULL DEFAULT 0,
    hp_mp_used integer NOT NULL DEFAULT 0,
    job smallint NOT NULL DEFAULT 0,
    skin_colour smallint NOT NULL DEFAULT 0,
    gender smallint NOT NULL DEFAULT 0,
    fame smallint NOT NULL DEFAULT 0,
    quest_fame integer NOT NULL DEFAULT 0,
    hair integer NOT NULL DEFAULT 0,
    face integer NOT NULL DEFAULT 0,
    ap smallint NOT NULL DEFAULT 0,
    sp character varying(128) NOT NULL DEFAULT '0,0,0,0,0,0,0,0,0,0'::character varying,
    map integer NOT NULL DEFAULT 0,
    spawn_point smallint NOT NULL DEFAULT 0,
    gm smallint NOT NULL DEFAULT 0,
    party integer NOT NULL DEFAULT 0,
    buddy_capacity integer NOT NULL DEFAULT 25,
    create_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    rank integer NOT NULL DEFAULT 1,
    rank_move integer NOT NULL DEFAULT 0,
    job_rank integer NOT NULL DEFAULT 1,
    job_rank_move integer NOT NULL DEFAULT 0,
    guild_id integer NOT NULL DEFAULT 0,
    guild_rank integer NOT NULL DEFAULT 5,
    messenger_id integer NOT NULL DEFAULT 0,
    messenger_position integer NOT NULL DEFAULT 4,
    mount_level integer NOT NULL DEFAULT 1,
    mount_exp integer NOT NULL DEFAULT 0,
    mount_tiredness integer NOT NULL DEFAULT 0,
    omok_wins integer NOT NULL DEFAULT 0,
    omok_losses integer NOT NULL DEFAULT 0,
    omok_ties integer NOT NULL DEFAULT 0,
    match_card_wins integer NOT NULL DEFAULT 0,
    match_card_losses integer NOT NULL DEFAULT 0,
    match_card_ties integer NOT NULL DEFAULT 0,
    merchant_mesos integer DEFAULT 0,
    has_merchant boolean DEFAULT false,
    equip_slots integer NOT NULL DEFAULT 24,
    use_slots integer NOT NULL DEFAULT 24,
    setup_slots integer NOT NULL DEFAULT 24,
    etc_slots integer NOT NULL DEFAULT 24,
    family_id integer NOT NULL DEFAULT '-1'::integer,
    monster_book_cover integer NOT NULL DEFAULT 0,
    alliance_rank integer NOT NULL DEFAULT 5,
    vanquisher_stage integer NOT NULL DEFAULT 0,
    ariant_points integer NOT NULL DEFAULT 0,
    dojo_points integer NOT NULL DEFAULT 0,
    last_dojo_stage integer NOT NULL DEFAULT 0,
    finished_dojo_tutorial boolean NOT NULL DEFAULT false,
    vanquisher_kills integer NOT NULL DEFAULT 0,
    summon_value integer NOT NULL DEFAULT 0,
    partner_id integer NOT NULL DEFAULT 0,
    marriage_item_id integer NOT NULL DEFAULT 0,
    rebirths integer NOT NULL DEFAULT 0,
    pq_points integer NOT NULL DEFAULT 0,
    data_string character varying(64) NOT NULL DEFAULT ''::character varying,
    last_logout_time timestamp without time zone NOT NULL DEFAULT '2015-01-01 05:00:00'::timestamp without time zone,
    last_exp_gain_time timestamp without time zone NOT NULL DEFAULT '2015-01-01 05:00:00'::timestamp without time zone,
    party_search boolean NOT NULL DEFAULT true,
    jail_expire integer NOT NULL DEFAULT 0
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX characters_pk ON characters(id int4_ops);
CREATE INDEX characters_id_account_id_name_index ON characters(id int4_ops,account_id int4_ops,name text_ops);
CREATE INDEX characters_id_account_id_world_index ON characters(id int4_ops,account_id int4_ops,world_id int4_ops);
